// src/lib/redirect-gen.ts
//
// Generates a static HTML redirect stub for a URL whose page is being retired
// (a flavor's slug or category segment changed, so its old URL will no
// longer be produced by src/pages' dynamic route templates).
//
// Astro (trailingSlash: 'always', output: 'static') copies everything under
// public/ into dist/ byte-for-byte, on top of whatever the page templates
// generate. So a stub written to public/flavors/{oldCategorySlug}/{oldSlug}/
// index.html becomes dist/flavors/{oldCategorySlug}/{oldSlug}/index.html at
// build time — exactly the URL the old page used to live at — as long as no
// real page template is still trying to generate that same route (that would
// be a genuine collision and is checked for below).

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const MODULE_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(MODULE_DIR, '..', '..');

const GENERATED_MARKER = '<!-- generated-by: redirect-gen.ts -->';

export interface GenerateRedirectOptions {
  /** Repo root override, for tests. Defaults to the real repo root. */
  repoRoot?: string;
  /** Overwrite an existing file at the target path even if it wasn't previously generated by this tool. Default false. */
  force?: boolean;
}

export interface GenerateRedirectResult {
  ok: boolean;
  /** Repo-relative path of the file that was (or would have been) written */
  filePath: string;
  wrote: boolean;
  reason?: string;
}

function normalizeUrlPath(p: string): string {
  let out = p.trim();
  if (!out.startsWith('/')) out = '/' + out;
  if (!out.endsWith('/')) out += '/';
  return out;
}

/**
 * True if `urlPath` (e.g. "/flavors/cane-sugar-syrups/american-strawberry/")
 * currently matches a live flavor in src/data/flavors.json — i.e. the real
 * page template would still generate a page at that exact route. Writing a
 * static redirect stub there would silently shadow (or collide with, in
 * Astro's own duplicate-route detection) that real page, so generateRedirect
 * refuses in that case: the underlying data (categorySlug/slug) must be
 * changed FIRST, then the redirect generated for the now-orphaned old URL.
 *
 * Reads flavors.json directly (not through content-store.ts) so this module
 * has no dependency on that file's landing.
 */
function urlPathIsCurrentlyRealFlavorRoute(urlPath: string, repoRoot: string): boolean {
  const flavorsPath = path.join(repoRoot, 'src', 'data', 'flavors.json');
  let flavors: any[];
  try {
    flavors = JSON.parse(fs.readFileSync(flavorsPath, 'utf8'));
  } catch {
    return false; // can't verify -> don't block on something we can't check
  }
  const normalized = normalizeUrlPath(urlPath);
  return flavors.some((f) => normalizeUrlPath(`/flavors/${f.categorySlug}/${f.slug}/`) === normalized);
}

function renderRedirectHtml(newPath: string): string {
  const escaped = newPath.replace(/"/g, '&quot;');
  return `<!doctype html>
${GENERATED_MARKER}
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="refresh" content="0;url=${escaped}">
<link rel="canonical" href="${escaped}">
<title>This page has moved</title>
<script>location.replace(${JSON.stringify(newPath)});</script>
</head>
<body>
<p>This page has moved. <a href="${escaped}">Click here if you are not redirected automatically.</a></p>
</body>
</html>
`;
}

/**
 * Write a static redirect stub so requesting `oldPath` serves a page that
 * immediately sends the visitor to `newPath`. Only ever call this AFTER the
 * underlying data (flavors.json's slug/category) has already been changed to
 * the new value — that's what makes `oldPath` a genuinely retired route
 * rather than one the real page template is still generating.
 */
export function generateRedirect(
  oldPath: string,
  newPath: string,
  options: GenerateRedirectOptions = {},
): GenerateRedirectResult {
  const repoRoot = options.repoRoot ?? REPO_ROOT;
  const normalizedOld = normalizeUrlPath(oldPath);
  const normalizedNew = normalizeUrlPath(newPath);

  const relFilePath = path.posix.join('public', normalizedOld, 'index.html').replace(/\/+/g, '/');
  const absFilePath = path.join(repoRoot, ...relFilePath.split('/'));

  if (normalizedOld === normalizedNew) {
    return { ok: false, filePath: relFilePath, wrote: false, reason: 'old and new paths are identical' };
  }

  if (urlPathIsCurrentlyRealFlavorRoute(normalizedOld, repoRoot)) {
    return {
      ok: false,
      filePath: relFilePath,
      wrote: false,
      reason:
        `"${normalizedOld}" still matches a live entry in src/data/flavors.json — the real page ` +
        `template would still generate a page at this route. Update the flavor's slug/category in ` +
        `the data first, then generate the redirect for the now-orphaned old path.`,
    };
  }

  if (fs.existsSync(absFilePath) && !options.force) {
    const existing = fs.readFileSync(absFilePath, 'utf8');
    if (!existing.includes(GENERATED_MARKER)) {
      return {
        ok: false,
        filePath: relFilePath,
        wrote: false,
        reason: `${relFilePath} already exists and was not created by redirect-gen — refusing to overwrite it. Pass { force: true } to override.`,
      };
    }
  }

  fs.mkdirSync(path.dirname(absFilePath), { recursive: true });
  fs.writeFileSync(absFilePath, renderRedirectHtml(normalizedNew), 'utf8');

  return { ok: true, filePath: relFilePath, wrote: true };
}
